name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Change directory
        run: cd ignite/reactjs/05-design-system

      - name: Checkout
        uses: actions/checkout@v3

      - name: Step NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Building
        run: npm run build

      - name: Deploy Storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
